#! /bin/bash
# $? is the return code from the last run process. 0 means no error happened. Other values represent some kind of unusual condition.

# With above example, you may know that in first statement both expressions are true,hence it returns true. But in last statement one expression is true and another is false, hence it returns false.

[ 4 -le 5 ] && [ 5 -le 7 ]; echo $?

[ 6 -le 5 ] && [ 5 -le 7 ]; echo $?

[ 4 -le 5 ] && [ 8 -le 7 ]; echo $?

[ 6 -le 5 ] && [ 8 -le 7 ]; echo $?
