#! /bin/bash
if [ $# -eq "3" ];then
echo "El número de parámetros introducidos es: " $#
else
echo "EL número de parámetros es incorrecto"
fi

--  OTRA FORMA --
clear
if [ $# -eq 3 ]
then
echo "El número de parámetros que has introducido es igual a $#"
else
echo "El número de parámetros que has introducido no es 3 sino $#"
fi

--  OTRA FORMA --
clear
if [ $# -eq 3 ];then
echo "El número de parámetros que has introducido es igual a $#"
else
echo "El número de parámetros que has introducido no es 3 sino $#"
fi

--  OTRA FORMA --
clear
if test $# -eq 3 
then
echo "El número de parámetros que has introducido es igual a $#"
else
echo "El número de parámetros que has introducido no es 3 sino $#"
fi

--  OTRA FORMA --
clear
if [ $# -eq 3 ];then echo "El número de parámetros que has introducido es igual a $#"
else
echo "El número de parámetros que has introducido no es 3 sino $#"
fi
