#! /bin/bash

clear
suma=0
for ((i=1;i<=$1;i++))
do

suma=`expr $suma + $i`
echo $i $suma
done
echo el resultado de la suma es:$suma


-- OTRA FORMA --

clear
suma=0
for ((i=1;i<=$1;i=i+1))
do
suma=$(($i+$suma))
done
echo $suma
