#! /bin/bash
count=1
#obtenga el contenido del archivo y luego pase a leer el comando iterando sobre las lines de comando while
cat myfile | while read line; do
echo "#$count: $line"
count=$(($count + 1))
done
echo "terminado"
 
